name: Create docker images

on:
  push:
    branches:
      - analytics
      - cloud

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate random hash
        id: random_hash
        run: echo "hash=$(openssl rand -hex 4)" >> $GITHUB_OUTPUT

